build:
  nodes:
    coverage:
      tests:
        override:
          - php-scrutinizer-run
          - command: ./vendor/bin/phpunit --coverage-clover coverage.xml
            coverage:
              file: coverage.xml
              format: clover
